from typing import Any


class Scene:
    def __init__(self) -> None: ...
    def load(self, *args, **kwargs) -> None: ...
    def unload(self) -> Any: ...
    def update(self) -> None: ...
    def render(self) -> None: ...
